version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/test/django/Dockerfile
    image: jukebox_radio_test_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    ports:
      - "8000:8000"
    command: /start
