# Generated by Django 3.1.2 on 2020-11-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='encoded_spotify_access_token',
            new_name='encrypted_spotify_access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='encoded_spotify_refresh_token',
            new_name='encrypted_spotify_refresh_token',
        ),
    ]
