# Generated by Django 3.1.2 on 2021-03-11 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jukebox_radio.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210219_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=jukebox_radio.users.models.upload_to_profile_imgs)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
