# Generated by Django 3.1.2 on 2020-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_textcommentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='transcript',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
