# Generated by Django 3.1.2 on 2021-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_auto_20210211_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="textcommentmodification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
