# Generated by Django 3.1.2 on 2020-12-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='is_playing',
        ),
        migrations.RemoveField(
            model_name='streamevent',
            name='is_playing',
        ),
    ]
