# Generated by Django 3.1.2 on 2020-12-31 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='next_queue_ptr',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='parent_queue_ptr',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='play_bass_stem',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='play_drums_stem',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='play_other_stem',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='play_vocals_stem',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='play_with_stem_separation',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='prev_queue_ptr',
        ),
        migrations.AddField(
            model_name='queue',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='streams.queue'),
        ),
    ]
