# Generated by Django 3.1.2 on 2021-01-15 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_collection_duration_ms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0002_auto_20210105_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='start_at',
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
