# Generated by Django 3.1.2 on 2021-01-15 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0003_auto_20210115_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueInterval',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_muted', models.BooleanField()),
                ('repeat_count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lower_bound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streams.marker')),
                ('queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streams.queue')),
                ('upper_bound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='streams.marker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
