# Generated by Django 3.1.2 on 2021-05-19 20:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_auto_20210512_0615"),
        ("streams", "0004_marker_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queue",
            name="played_at",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="paused_at",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="recording_ended_at",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="recording_started_at",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="started_at",
        ),
        migrations.RemoveField(
            model_name="streamevent",
            name="paused_at",
        ),
        migrations.RemoveField(
            model_name="streamevent",
            name="recording_ended_at",
        ),
        migrations.RemoveField(
            model_name="streamevent",
            name="recording_started_at",
        ),
        migrations.RemoveField(
            model_name="streamevent",
            name="started_at",
        ),
        migrations.AddField(
            model_name="queue",
            name="duration_ms",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queue",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="queue",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued_init", "Queued (init)"),
                    ("played", "Played"),
                    ("paused", "Paused"),
                    ("ended_auto", "Ended (auto)"),
                    ("ended_skip", "Ended (skipped)"),
                    ("queued_previous", "Queued (previous)"),
                ],
                default="paused",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="queue",
            name="status_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 5, 19, 20, 56, 6, 414860, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marker",
            name="track",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markers",
                to="music.track",
            ),
        ),
    ]
