# Generated by Django 3.1.2 on 2021-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20210519_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueinterval',
            name='stem_bass',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueinterval',
            name='stem_drums',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueinterval',
            name='stem_other',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueinterval',
            name='stem_piano',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queueinterval',
            name='stem_vocals',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
