# Generated by Django 3.1.2 on 2021-01-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20210117_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueinterval',
            name='repeat_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
