# Generated by Django 3.1.2 on 2020-11-09 23:16

from django.db import migrations, models
import django.db.models.deletion
import jukebox_radio.music.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('album', 'Album'), ('playlist', 'Playlist'), ('mix', 'Mix')], max_length=32)),
                ('provider', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube'), ('jukebox_radio', 'Jukebox Radio')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('duration_ms', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to=jukebox_radio.music.models.upload_to_tracks_jr_imgs)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('spotify', 'Spotify'), ('youtube', 'YouTube'), ('jukebox_radio', 'Jukebox Radio')], max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('duration_ms', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=200, null=True)),
                ('audio', models.FileField(null=True, upload_to=jukebox_radio.music.models.upload_to_tracks_jr_audios)),
                ('img', models.ImageField(null=True, upload_to=jukebox_radio.music.models.upload_to_tracks_jr_imgs)),
                ('img_url', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.collection',),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.collection',),
        ),
        migrations.CreateModel(
            name='CollectionListing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_collection_listings', to='music.collection')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'unique_together': {('track', 'collection', 'number')},
            },
        ),
    ]
