# Generated by Django 3.1.2 on 2020-12-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stem',
            old_name='format',
            new_name='instrument',
        ),
    ]
