# Generated by Django 3.1.2 on 2020-11-11 05:43

from django.db import migrations, models
import jukebox_radio.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=jukebox_radio.music.models.upload_to_tracks_jr_imgs),
        ),
        migrations.AlterField(
            model_name='track',
            name='img_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
