# Generated by Django 3.1.2 on 2020-11-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='artist_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
