# Generated by Django 3.1.2 on 2020-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
