# Generated by Django 3.1.2 on 2020-11-11 05:44

from django.db import migrations, models
import jukebox_radio.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201111_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=jukebox_radio.music.models.upload_to_tracks_jr_audios),
        ),
    ]
