# Generated by Django 3.1.2 on 2020-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201213_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='artist_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(),
        ),
    ]
