# Generated by Django 3.1.2 on 2020-11-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_collection_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
