# Generated by Django 3.1.2 on 2020-12-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_album_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('provider', 'external_id')},
        ),
    ]
