# Generated by Django 3.1.2 on 2021-05-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210314_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='provider',
            field=models.CharField(choices=[('apple_music', 'Apple Music'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('audius', 'Audius'), ('jukebox_radio', 'Jukebox Radio')], max_length=32),
        ),
        migrations.AlterField(
            model_name='track',
            name='provider',
            field=models.CharField(choices=[('apple_music', 'Apple Music'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('audius', 'Audius'), ('jukebox_radio', 'Jukebox Radio')], max_length=32),
        ),
    ]
