# Generated by Django 3.1.2 on 2020-12-15 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20201214_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stem',
            name='id',
        ),
        migrations.AddField(
            model_name='stem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
