# Generated by Django 3.1.2 on 2021-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_auto_20210510_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("spotify", "Spotify"),
                    ("youtube", "YouTube"),
                    ("apple_music", "Apple Music"),
                    ("audius", "Audius"),
                    ("jukebox_radio", "Jukebox Radio"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="provider",
            field=models.CharField(
                choices=[
                    ("spotify", "Spotify"),
                    ("youtube", "YouTube"),
                    ("apple_music", "Apple Music"),
                    ("audius", "Audius"),
                    ("jukebox_radio", "Jukebox Radio"),
                ],
                max_length=32,
            ),
        ),
    ]
