# Generated by Django 3.1.2 on 2021-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210512_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem',
            name='instrument',
            field=models.CharField(choices=[('bass', 'Bass'), ('drums', 'Drums'), ('vocals', 'Vocals'), ('piano', 'Piano'), ('other', 'Other')], max_length=32),
        ),
    ]
